### ISSUE TITLE
final work

### ISSUE THREAD

**Issue by Paccifficul** [Paccifficul/Something-new....#10]
@GalteXx

Сделал первые 4 пункта
Насчёт пятого: как понять, гистограмма неверна? Мы должны использовать bool IsHardСap для проверки?

**Comment by GalteXx** [comment]
Блин, мне тут весь график сбили, я отвечаю в гите поздновато.
Никак. Достаточно просто перестроить диаграмму, не "саботируя" ее построение.

**Comment by GalteXx** [comment]
Если захочешь сдать 5 часть тагни еще раз

**Comment by Paccifficul** [comment]
@GalteXx 
Посмотри 5-й пункт
