### ISSUE TITLE
Метро - 1

### ISSUE THREAD

**Issue by Paccifficul** [Paccifficul/Something-new....#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Файл classStation.cs**
- 32 строка. Если присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Принято, только поправь ошибки.
