### ISSUE TITLE
Классная работа 9.11

### ISSUE THREAD

**Issue by Paccifficul** [Paccifficul/Something-new....#4]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- А попробуй-ка преобразовать методы GetPower, SetPower и аналогичные в свойства! Это будет более лаконичным решением :)
- 67-69 строка. Зачем еще раз писать this.label = label, если ты вызываешь базовый конструктор, куда передаешь часть параметров? В базовом конструкторе это и обработается, а ты как бы дважды выполняешь команду присвоения. А иначе базовый конструктор бесполезен.
- 155-157 строка. То же самое.

Всё остальное корректно, поправишь - зачту.

**Comment by Paccifficul** [comment]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Респект 👍, фишку со свойствами уловил. Принято.
