### ISSUE TITLE
Магазин муз дисков

### ISSUE THREAD

**Issue by Paccifficul** [Paccifficul/Something-new....#5]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Класс Disk:**
- 47 строка. Как только ты обратишься к свойству Price, у тебя выкинет исключение. Имплементировать ты имплементировал, а из свойства нужно сделать простое автосвойство.

Править не надо, но это на будущее.

**Comment by vdetstvepil** [comment]
Принято.
