### ISSUE TITLE
Homework 3 & Practice

### ISSUE THREAD

**Issue by Paccifficul** [Paccifficul/Something-new....#9]
@GalteXx

**Comment by GalteXx** [comment]
>BullSh1t
Миленько

Но не обязательно объединять только кнопки, лучше было пришить текстбокс. (ладно, ты успел сдать до того как я поправил тз, и так принял бы.
НО:
1) Ты забыл событие.
2) ForeGround и BackGround было бы логичнее сделать Brush
3) Width должен задавать размер всего объекта, а не отдельной его части. пользователю будет охх как неудобно потом просчитывать, домножать на 4 и пр.
4) Heigth аналогично
5) Content стоило сделать String
6) Раз уж тебе все равно вносить +- существенные правки, почему бы на TexBox не поменять?

Да, и еще enum был вовсе не обязателен. Ну раз уж сделал, можешь оставить.

**Comment by GalteXx** [comment]
Практику принял

**Comment by Paccifficul** [comment]
@GalteXx  посмотри домашку, я добавил событие
